spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  jwt:
    secret: lemorninglemorninglemorninglemorninglemorninglemorninglemorninglemorninglemorninglemorning
  datasource:
    url: jdbc:h2:tcp://localhost/~/lemorning
    username: sa
    password:
    driver-class-name: org.h2.Driver
  devtools:
    livereload:
      enabled: true   # 이 옵션은 정적 파일 변동 시 자동 반영될 수 있도록 돕는다.
  jpa:
    hibernate:
      ddl-auto: create  # 이 옵션은 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성한다
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace   # sql query 에 들어오는 파라메타 값 추적